#configfile: "config/all_neoseq_config.yaml"
#configfile: "config/all_controls_config.yaml"
configfile: "config/all_config.yaml"


import pandas as pd
table = pd.read_table(config["cohort_list"]).set_index("MRN", drop=False)
date_filter = table.loc[table["DOB"] >= "2020-01-01"]
count_filter = date_filter.loc[(date_filter["NOTE_CNT"] >= 3) & (date_filter["ICD10CM_CNT"] >= 3)]
cohort = count_filter.loc[count_filter["EXCLUDE"] == 0]


rule all:
	input:
		expand("output/{project}/notes2mpse/{patient}_clix4mpse.tsv", patient=cohort["MRN"].tolist(), project=config["project_id"]),
		expand("output/{project}/icd2mpse/{patient}_icd4mpse.tsv", patient=cohort["MRN"].tolist(), project=config["project_id"]),
		expand("output/{project}/clinphen2mpse/{patient}_clinphen4mpse.tsv", patient=cohort["MRN"].tolist(), project=config["project_id"])


rule get_notes:
	output:
		"output/{project}/get_notes/{patient}_notes.tsv"
	log:
		"output/{project}/logs/get_notes/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/get_notes/{patient}.txt"
	params:
		EDWRD=config["EDWRD"],
		sql=config["notes_sql"]
	shell:
		"python3 {params.EDWRD}/bin/custom_query.py "
		"-s {params.sql} "
		"-p {wildcards.patient} "
		"{output} "
		"2> {log}"


rule prep_clix:
	input:
		"output/{project}/get_notes/{patient}_notes.tsv"
	output:
		"output/{project}/prep_clix/{patient}_notes4clix.json"
	log:
		"output/{project}/logs/prep_clix/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/prep_clix/{patient}.txt"
	shell:
		"python3 bin/note_prepper.py "
		"--data {input} "
		"--type clix "
		"{output} "
		"2> {log}"


rule clix:
	input:
		"output/{project}/prep_clix/{patient}_notes4clix.json"
	output:
		"output/{project}/clix/{patient}_clix.tsv"
	log:
		"output/{project}/logs/clix/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/clix/{patient}.txt"
	params:
		clinithink=config["clinithink"],
		secret=config["apisecret"]
	resources:
		runtime=20
	shell:
		"python3 {params.clinithink}/bin/rapid_clix2.py "
		"-d {input} "
		"-s {params.secret} "
		"--abstractions "
		"{output} "
		"2> {log}"


rule clix2mpse:
	input:
		"output/{project}/clix/{patient}_clix.tsv"
	output:
		"output/{project}/clix2mpse/{patient}_clix4mpse.tsv"
	log:
		"output/{project}/logs/clix2mpse/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/clix2mpse/{patient}.txt"
	params:
		master=config["master"]
	shell:
		"python3 bin/mpse_prepper.py "
		"-d {input} "
		"-M {params.master} "
		"--type clix "
		#"--timestamps "
		"{output} "
		"2> {log}"


rule notes_mpse:
	input:
		"output/{project}/clix2mpse/{patient}_clix4mpse.tsv"
	output:
		"output/{project}/notes_mpse/{patient}_mpse_predictions.tsv"
	log:
		"output/{project}/logs/notes_mpse/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/notes_mpse/{patient}.txt"
	params:
		mpse=config["mpse"]
	shell:
		"python3 {params.mpse}/bin/mpse.py "
		"-m {config[model]} "
		"-p {input} "
		#"--timestamps "
		"-o output/{wildcards.project}/mpse "
		"> {output} "
		"2> {log}"


rule prep_clinphen:
	input:
		"output/{project}/get_notes/{patient}_notes.tsv"
	output:
		"output/{project}/prep_clinphen/{patient}_notes4clinphen.tsv"
	log:
		"output/{project}/logs/prep_clinphen/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/prep_clinphen/{patient}.txt"
	shell:
		"python3 bin/note_prepper.py "
		"--data {input} "
		"--type clinphen "
		"{output} "
		"2> {log}"


rule clinphen:
	input:
		"output/{project}/prep_clinphen/{patient}_notes4clinphen.tsv"
	output:
		"output/{project}/clinphen/{patient}_clinphen.tsv"
	log:
		"output/{project}/logs/clinphen/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/clinphen/{patient}.txt"
	params:
		clinphen=config["clinphen"]
	resources:
		runtime=20
	shell:
		"python3 {params.clinphen}/clinphen_bulk "
		"--delim $'\t' "
		"--patcol pid "
		"--notecol text "
		#"--threads {workflow.cores} "
		"{input} "
		"{output} "
		"2> {log}"


rule clinphen2mpse:
	input:
		"output/{project}/clinphen/{patient}_clinphen.tsv"
	output:
		"output/{project}/clinphen2mpse/{patient}_clinphen4mpse.tsv"
	log:
		"output/{project}/logs/clinphen2mpse/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/clinphen2mpse/{patient}.txt"
	params:
		master=config["master"]
	shell:
		"python3 bin/mpse_prepper.py "
		"-d {input} "
		"-M {params.master} "
		"--type clinphen "
		#"--timestamps "
		"{output} "
		"2> {log}"


rule clinphen_mpse:
	input:
		"output/{project}/clinphen2mpse/{patient}_clinphen4mpse.tsv"
	output:
		"output/{project}/clinphen_mpse/{patient}_mpse_predictions.tsv"
	log:
		"output/{project}/logs/clinphen_mpse/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/clinphen_mpse/{patient}.txt"
	params:
		mpse=config["mpse"]
	shell:
		"python3 {params.mpse}/bin/mpse.py "
		"-m {config[model]} "
		"-p {input} "
		#"--timestamps "
		"-o output/{wildcards.project}/mpse "
		"> {output} "
		"2> {log}"


rule get_icd10:
	output:
		"output/{project}/get_icd10/{patient}_icd10cm.tsv"
	log:
		"output/{project}/logs/get_icd10/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/get_icd10/{patient}.txt"
	params:
		EDWRD=config["EDWRD"],
		sql=config["icd10_sql"]
	shell:
		"python3 {params.EDWRD}/bin/custom_query.py "
		"-s {params.sql} "
		"-p {wildcards.patient} "
		"{output} "
		"2> {log}"


rule icd2mpse:
	input:
		"output/{project}/get_icd10/{patient}_icd10cm.tsv"
	output:
		"output/{project}/icd2mpse/{patient}_icd4mpse.tsv"
	log:
		"output/{project}/logs/icd2mpse/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/icd2mpse/{patient}.txt"
	params:
		master=config["master"]
	shell:
		"python3 bin/mpse_prepper.py "
		"-d {input} "
		"-M {params.master} "
		"--type icd10 "
		#"--timestamps "
		"{output} "
		"2> {log}"


rule icd10_mpse:
	input:
		"output/{project}/icd2mpse/{patient}_icd4mpse.tsv"
	output:
		"output/{project}/icd10_mpse/{patient}_mpse_predictions.tsv"
	log:
		"output/{project}/logs/icd10_mpse/{patient}.log"
	benchmark:
		"output/{project}/benchmarks/icd10_mpse/{patient}.txt"
	params:
		mpse=config["mpse"]
	shell:
		"python3 {params.mpse}/bin/mpse.py "
		"-m {config[model]} "
		"-p {input} "
		#"--timestamps "
		"-o output/{wildcards.project}/mpse "
		"> {output} "
		"2> {log}"
